doctrine_odm.mongodb:
    # single document manager config
    mappings:                 {}
    #    MyBundle5:
    #        type:  yml   # annotations, xml, yml, php or static-php
    #        dir:   Resources/config/doctrine/mapping
    #        alias: BundleAlias
    default_document_manager: default
    default_database:         default
    metadata_cache_driver:    array

    # multiple document manager configuration
    document_managers:  {}
    #    dm1:
    #        connection:             default
    #        metadata_cache_driver:  xcache
    #        mappings:               {}

    # single connection configuration
    default_connection: default
    server:             ~
    options:            {}

    # multiple connection configuration
    connections:        {}
    #    conn1:
    #        server: mongodb://localhost:27017
    #        options:
    #            connect: true

    # proxy and hydrator class configuration
    proxy_namespace:                ~
    auto_generate_proxy_classes:    ~
    hydrator_namespace:             ~
    auto_generate_hydrator_classes: ~